### PR TITLE
Fixed not completing refresh tokens

### PR DESCRIPTION
**Pull request by jaxoncreed**
A fix for https://github.com/solid/node-solid-server/issues/1533.

Note this has not been thoroughly tested

### CODE REVIEW

**Comment by matthieubosquet** [comment]
LGTM! :)

**Review by matthieubosquet — APPROVED** [review]

**Comment by bourgeoa** [comment]
https://github.com/solid/oidc-op/blob/72e4cfa7870aab7913314cbbe5277d0bb559dcf8/test/handlers/TokenRequestSpec.js#L1366
Is there a possibility to fill the test ?

**Comment by jaxoncreed** [comment]
Okay added tests

**Comment by bourgeoa** [comment]
Wonderful

**Comment by matthieubosquet** [comment]
@bourgeoa do you think you could cut a patch release in order to test the fix on NSS on our side?

**Comment by bourgeoa** [comment]
Ok I shall do it first on the https://solicommunity.net:8443 test server.

**Comment by matthieubosquet** [comment]
Thank you @bourgeoa! :)

**Comment by bourgeoa** [comment]
@jaxoncreed @michielbdejong Can one of you add me to npm. I cannot publish.
If not can you publish 0.11.2 I have updated the package.json to 0.11.2 and dependencies.

**Comment by bourgeoa** [comment]
@michielbdejong I do not have access to npm publish on this repo : can you give me access and if not possible can you publish 0.11.2 I have updated package.json.

**Comment by bourgeoa** [comment]
@matthieubosquet 
> Note this has not been thoroughly tested

Could you check that refresh token is working as expected on the test-server https://solidcommunity.net:8443 ?

**Comment by matthieubosquet** [comment]
```
POST /token HTTP/1.1
Host: solidcommunity.net:8443
Content-Type: application/x-www-form-urlencoded
Content-Length: 161
grant_type=refresh_token&refresh_token=XXX&client_id=XXX&client_secret=XXX
```

Still gives a 500 error I'm afraid.

**Comment by bourgeoa** [comment]
@matthieubosquet Sorry I missed the update should be correct now. Could you retry

**Comment by matthieubosquet** [comment]
@bourgeoa @jaxoncreed apparently, we're still missing 1 thing, returning an ID token. @NSeydoux suggested a fix there: https://github.com/solid/oidc-op/pull/32

Could you see if it makes sense/push/deploy?

**Comment by bourgeoa** [comment]
@matthieubosquet
I am fully ignorant in this area so : 
I manually patched https://solidcommunity.net:8443 with @NSeydoux fix.
Could you check the result.

If OK I could push/deploy

**Comment by matthieubosquet** [comment]
@NSeydoux 's fix works! ;)

@bourgeoa it would be fabulous if you could get https://github.com/solid/oidc-op/pull/32 merged!

**Pull request merged**
