### PR TITLE
Solid expects OAuth token's 'aud' claim to include 'sub'.

### PR DESCRIPTION
**Pull request by cblakeley**
Relates to: <https://github.com/solid/node-solid-server/issues/1061>

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Based on the discussion in https://github.com/solid/node-solid-server/issues/1061, I confirm that this PR indeed adds `sub` to the `aud` array (enforcing the latter to be an array).

What I am missing in https://github.com/solid/node-solid-server/issues/1061, is an indication that `aud` MUST include `iss` or `sub`. Do we have a source to back that up?

Also, given that the tests use dummy data, in the case of Solid, would `sub` be the WebID of the user?

**Comment by cblakeley** [comment]
> What I am missing in solid/node-solid-server#1061, is an indication that aud MUST include iss or sub. Do we have a source to back that up?

<https://tools.ietf.org/html/rfc7519#section-4.1.3> says "The interpretation of audience values is generally application specific."; so for access tokens[1] does this imply that 'aud' can contain any form of identifier to identify the access token recipient? Is the recipient is this context NSS? If so 'sub' (a WebID from the issuer) in effect identifies the recipient, though including 'iss' rather than 'sub' in 'aud' would identify the recipient equally well? 

[1] For ID tokens, `aud` must contain the `client_id`. ([OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html#IDToken))

I added 'sub', rather than 'iss', to 'aud' in order to satisfy `filterAudience()/domainMatches()`, but I don't know why the test applied by `domainMatches()` is enforced. @dmitrizagidulin: Please could you clarify?

> Also, given that the tests use dummy data, in the case of Solid, would sub be the WebID of the user?

When I decoded an access token, `sub` did contain my WebID.

From: https://github.com/solid/node-solid-server/issues/1061#issue-402326751

> Decoding the oauth token (a JWT) using https://jwt.io/
> 
> ```
> {
>   "iss": "https://solid.openlinksw.com:8444",
>   "sub": "https://cmsblakeley.solid.openlinksw.com:8444/profile/card#me",
>   "aud": "79888c62ca35e4b89665f328b494600b",
>   "exp": 1549385146,
>   "iat": 1548175546,
>   "jti": "5709a267c48596e8",
>   "scope": "openid profile email"
> }
> ```

**Comment by RubenVerborgh** [comment]
> [1] For ID tokens, `aud` must contain the `client_id`.

Yes, but `sub` does not seem to be that.

**Comment by kidehen** [comment]
@RubenVerborgh ,

What are we supposed to do with the statement below? 

> While it might make things work, it seems to be a correct solution to the wrong problem. I believe we need a fix elsewhere.

**Comment by RubenVerborgh** [comment]
@kidehen Here is what we know:
- `OidcManager#filterAudience` expects `sub` in `aud`

Here is what we don't know:
- should `sub` be in `aud`?
- should `OidcManager#filterAudience` use `sub` instead?
- are the checks in `OidcManager#filterAudience` correct and necessary?

This PR assumes yes/no/no, but we have no indication that this is correct.

> What are we supposed to do with the statement below?

There's a couple of possible actions, all of which can be helpful in isolation or combination:

1. wait on input from @dmitrizagidulin
2. build an argumentation for why the problem is missing `sub` in `aud`
3. build an argumentation for why the problem is `OidcManager#filterAudience` is wrong to expect `sub` in `aud`

**Comment by cblakeley** [comment]
> > [1] For ID tokens, `aud` must contain the `client_id`.
> 
> Yes, but `sub` does not seem to be that.

@RubenVerborgh Just to clarify - this issue relates to access tokens, not ID tokens.

**Comment by dmitrizagidulin** [comment]
(Apologies for the delay, everyone, I'm currently in a meeting with @justinwb, talking about some of these issues, I'll fill in the background for the relevant specs ([PoP Semantics for JWTs](https://tools.ietf.org/html/rfc7800) and https://tools.ietf.org/html/draft-ietf-oauth-pop-key-distribution-03) shortly)

**Comment by kidehen** [comment]
@RubenVerborgh ,

Currently, the issue is now as follows:

If the current PR is applied as is, both OidcManager and oidc-op break, right ?

**Comment by cblakeley** [comment]
As I see it, because of `OidcManager#filterAudience`, `OidcManager` is imposing a requirement on `oidc-op` that `aud` includes `sub`. It's imposing a coupling/dependency which shouldn't be there. (So this PR satisfies the requirement as a workaround, but doesn't remove the dependency).

The contents of `aud` are set by `AccessToken#issueForRequest`. If the interpretation of the contents of `aud` is done by a caller using an instance of `AccessToken`, should there be a way for the caller to augment the contents of `aud` with the recipient identifiers it recognizes?

**Comment by dmitrizagidulin** [comment]
@kidehen 
> what is the solution i.e., do you have an alternative of are you claiming the current behavior is fine?

So, the root cause is confusion about the tokens the auth client is using. There's no server side code changes needed, the audience filtering mechanism is working exactly as designed (and as recommended in the specs).

The client side code should be adjusted to either generate regular OIDC tokens, or use the PoP tokens through the auth client (instead of passing them manually in the request). I'll go into more details on the related issue thread.

**Comment by RubenVerborgh** [comment]
It is my understanding that this fix is not addressing the right problem, so closing for now. Following up in the other thread for an appropriate solution.

**Pull request closed without merging**
